spring.application.name=mybatis

# db url
spring.datasource.url=jdbc:h2:mem:testdb

# db driver
spring.datasource.driver-class-name=org.h2.Driver

# db username
spring.datasource.username=sa

# db password
spring.datasource.password=password

# h2 console
spring.h2.console.enabled=true

# mybatis xml mapper location
mybatis.mapper-locations=classpath:mapper/**/*.xml
